In [2]:
import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
df = pd.read_csv("../data/Churn_Modelling.csv")

df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.drop(
    columns=["RowNumber", "CustomerId", "Surname"],
    inplace=True
)

df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
X = df.drop("Exited", axis=1)
y = df["Exited"]

print(X.shape)
print(y.shape)

(10000, 10)
(10000,)

In [6]:
X = pd.get_dummies(
    X,
    columns=["Geography", "Gender"],
    drop_first=True
)

X.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,True,False

In [7]:
with open("../models/training_columns.pkl", "wb") as f:
    pickle.dump(X.columns.tolist(), f)

print("training_columns.pkl saved")

training_columns.pkl saved

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

with open("../models/scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

print("scaler.pkl saved")

scaler.pkl saved

In [10]:
model = Sequential()

model.add(
    Dense(
        units=16,
        activation="relu",
        input_shape=(X_train.shape[1],)
    )
)

model.add(
    Dense(
        units=8,
        activation="relu"
    )
)

model.add(
    Dense(
        units=1,
        activation="sigmoid"
    )
)

model.summary()

c:\Users\yanal\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           192 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 337 (1.32 KB)

 Trainable params: 337 (1.32 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [12]:
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.1
)

Epoch 1/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7644 - loss: 0.5228 - val_accuracy: 0.8062 - val_loss: 0.4411
Epoch 2/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7976 - loss: 0.4491 - val_accuracy: 0.8138 - val_loss: 0.4168
Epoch 3/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8047 - loss: 0.4309 - val_accuracy: 0.8138 - val_loss: 0.4051
Epoch 4/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8158 - loss: 0.4156 - val_accuracy: 0.8250 - val_loss: 0.3957
Epoch 5/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8310 - loss: 0.3998 - val_accuracy: 0.8400 - val_loss: 0.3840
Epoch 6/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8396 - loss: 0.3838 - val_accuracy: 0.8438 - val_loss: 0.3732
Epoch 7/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8449 - loss: 0.3701 - val_accuracy: 0.8450 - val_loss: 0.3626
Epoch 8/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8515 - loss: 0.3592 - val_accuracy: 0.8450 - val_loss: 0.3550
Epoch 9/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8578 - loss: 0.3514 - val_accuracy: 0.8537 - val_loss: 0.3484
Epoch 10/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8587 - loss: 0.3468 - val_accuracy: 0.8537 - val_loss: 0.3453
Epoch 11/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8579 - loss: 0.3431 - val_accuracy: 0.8562 - val_loss: 0.3412
Epoch 12/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8600 - loss: 0.3406 - val_accuracy: 0.8537 - val_loss: 0.3395
Epoch 13/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8607 - loss: 0.3383 - val_accuracy: 0.8500 - val_loss: 0.3399
Epoch 14/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8599 - loss: 0.3371 - val_accuracy: 0.8537 - val_loss: 0.3392
Epoch 15/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8618 - loss: 0.3353 - val_accuracy: 0.8537 - val_loss: 0.3405
Epoch 16/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8621 - loss: 0.3347 - val_accuracy: 0.8550 - val_loss: 0.3389
Epoch 17/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8618 - loss: 0.3331 - val_accuracy: 0.8575 - val_loss: 0.3367
Epoch 18/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8621 - loss: 0.3323 - val_accuracy: 0.8550 - val_loss: 0.3385
Epoch 19/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8607 - loss: 0.3317 - val_accuracy: 0.8600 - val_loss: 0.3359
Epoch 20/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8612 - loss: 0.3311 - val_accuracy: 0.8562 - val_loss: 0.3359
Epoch 21/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8597 - loss: 0.3303 - val_accuracy: 0.8512 - val_loss: 0.3373
Epoch 22/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8625 - loss: 0.3293 - val_accuracy: 0.8537 - val_loss: 0.3382
Epoch 23/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8617 - loss: 0.3294 - val_accuracy: 0.8587 - val_loss: 0.3351
Epoch 24/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8618 - loss: 0.3285 - val_accuracy: 0.8512 - val_loss: 0.3355
Epoch 25/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3280 - val_accuracy: 0.8562 - val_loss: 0.3366
Epoch 26/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8649 - loss: 0.3274 - val_accuracy: 0.8575 - val_loss: 0.3371
Epoch 27/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8619 - loss: 0.3273 - val_accuracy: 0.8537 - val_loss: 0.3368
Epoch 28/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8615 - loss: 0.3272 - val_accuracy: 0.8575 - val_loss: 0.3338
Epoch 29/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8642 - loss: 0.3265 - val_accuracy: 0.8587 - val_loss: 0.3331
Epoch 30/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8639 - loss: 0.3262 - val_accuracy: 0.8575 - val_loss: 0.3329
Epoch 31/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8632 - loss: 0.3259 - val_accuracy: 0.8562 - val_loss: 0.3337
Epoch 32/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8644 - loss: 0.3258 - val_accuracy: 0.8562 - val_loss: 0.3339
Epoch 33/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8660 - loss: 0.3250 - val_accuracy: 0.8587 - val_loss: 0.3344
Epoch 34/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8649 - loss: 0.3252 - val_accuracy: 0.8587 - val_loss: 0.3346
Epoch 35/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8654 - loss: 0.3242 - val_accuracy: 0.8512 - val_loss: 0.3352
Epoch 36/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8635 - loss: 0.3245 - val_accuracy: 0.8600 - val_loss: 0.3325
Epoch 37/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8646 - loss: 0.3239 - val_accuracy: 0.8575 - val_loss: 0.3352
Epoch 38/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8633 - loss: 0.3233 - val_accuracy: 0.8600 - val_loss: 0.3361
Epoch 39/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8668 - loss: 0.3235 - val_accuracy: 0.8550 - val_loss: 0.3346
Epoch 40/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8656 - loss: 0.3231 - val_accuracy: 0.8600 - val_loss: 0.3337
Epoch 41/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8665 - loss: 0.3229 - val_accuracy: 0.8562 - val_loss: 0.3334
Epoch 42/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8653 - loss: 0.3229 - val_accuracy: 0.8600 - val_loss: 0.3330
Epoch 43/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8657 - loss: 0.3223 - val_accuracy: 0.8625 - val_loss: 0.3340
Epoch 44/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8664 - loss: 0.3221 - val_accuracy: 0.8575 - val_loss: 0.3355
Epoch 45/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8651 - loss: 0.3222 - val_accuracy: 0.8562 - val_loss: 0.3355
Epoch 46/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8644 - loss: 0.3219 - val_accuracy: 0.8600 - val_loss: 0.3331
Epoch 47/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8650 - loss: 0.3221 - val_accuracy: 0.8575 - val_loss: 0.3349
Epoch 48/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8664 - loss: 0.3216 - val_accuracy: 0.8600 - val_loss: 0.3348
Epoch 49/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8651 - loss: 0.3211 - val_accuracy: 0.8587 - val_loss: 0.3360
Epoch 50/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8674 - loss: 0.3213 - val_accuracy: 0.8575 - val_loss: 0.3353

In [13]:
loss, accuracy = model.evaluate(
    X_test,
    y_test
)

print("Accuracy:", accuracy)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8605 - loss: 0.3378
Accuracy: 0.8604999780654907

In [14]:
model.save("../models/ann_model.keras")

print("ann_model.keras saved successfully")

ann_model.keras saved successfully

In [15]:
sample = X.iloc[[0]]

scaled_sample = scaler.transform(sample)

prediction = model.predict(scaled_sample)

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
[[0.34416175]]